import DirectionalFriction.Operator

/-!
# Operator envelope identity

Phase 2 formalization of Proposition T4 on a slack-floor interior branch.  The
minimized fixed-fleet waiting cost is differentiated in Lean and its derivative
is identified with the directional access-cost difference faced by the marginal
shopper.
-/

namespace DirectionalFriction.Envelope

open DirectionalFriction.Operator

noncomputable section

/-- Canonical `H(x,M)` on a slack-floor branch. -/
def H (M x : ℝ) : ℝ :=
  (1 - M - 2 * x) /
    Real.sqrt (demandL M x * demandR x)

/-- Minimized aggregate waiting cost, including the common scale `A=w/F`. -/
def waitingCost (A M x : ℝ) : ℝ :=
  A * minimizedCost M x

/-- Directional waiting/access difference generated by the optimal service
    allocation, before multiplication by `A`. -/
def accessDifference (M x : ℝ) : ℝ :=
  1 / unconstrainedShare M x - 1 / (1 - unconstrainedShare M x)

/-- Algebraic coefficient produced by differentiating the two square roots. -/
theorem raw_derivative_eq_H {M x : ℝ}
    (hL : 0 < demandL M x)
    (hR : 0 < demandR x) :
    (1 / (2 * Real.sqrt (demandL M x)) +
        (-1) / (2 * Real.sqrt (demandR x))) *
        (Real.sqrt (demandL M x) + Real.sqrt (demandR x)) +
      (Real.sqrt (demandL M x) + Real.sqrt (demandR x)) *
        (1 / (2 * Real.sqrt (demandL M x)) +
          (-1) / (2 * Real.sqrt (demandR x))) = H M x := by
  have hsL : 0 < Real.sqrt (demandL M x) := Real.sqrt_pos.2 hL
  have hsR : 0 < Real.sqrt (demandR x) := Real.sqrt_pos.2 hR
  have hsqL : (Real.sqrt (demandL M x)) ^ 2 = demandL M x :=
    Real.sq_sqrt (le_of_lt hL)
  have hsqR : (Real.sqrt (demandR x)) ^ 2 = demandR x :=
    Real.sq_sqrt (le_of_lt hR)
  rw [H, Real.sqrt_mul (le_of_lt hL)]
  field_simp [ne_of_gt hsL, ne_of_gt hsR]
  rw [← hsqL, ← hsqR]
  unfold demandL demandR
  ring

/-- The normalized minimized operator cost has derivative `H(x,M)`. -/
theorem hasDerivAt_minimizedCost {M x : ℝ}
    (hL : 0 < demandL M x)
    (hR : 0 < demandR x) :
    HasDerivAt (fun y : ℝ => minimizedCost M y) (H M x) x := by
  have hDL : HasDerivAt (fun y : ℝ => demandL M y) 1 x := by
    simpa [demandL] using (hasDerivAt_id x).const_add M
  have hDR : HasDerivAt (fun y : ℝ => demandR y) (-1) x := by
    simpa [demandR] using (hasDerivAt_const x (1 : ℝ)).sub (hasDerivAt_id x)
  have hsL := hDL.sqrt (ne_of_gt hL)
  have hsR := hDR.sqrt (ne_of_gt hR)
  have hsum := hsL.add hsR
  have hraw := hsum.mul hsum
  have hcoef := raw_derivative_eq_H hL hR
  simpa [minimizedCost, pow_two, hcoef] using hraw

/-- Proposition T4's derivative statement with the waiting-cost scale restored. -/
theorem hasDerivAt_waitingCost {A M x : ℝ}
    (hL : 0 < demandL M x)
    (hR : 0 < demandR x) :
    HasDerivAt (fun y : ℝ => waitingCost A M y) (A * H M x) x := by
  simpa [waitingCost] using
    HasDerivAt.const_mul A (hasDerivAt_minimizedCost hL hR)

/-- Pointwise derivative form of the operator envelope identity. -/
theorem deriv_waitingCost {A M x : ℝ}
    (hL : 0 < demandL M x)
    (hR : 0 < demandR x) :
    deriv (fun y : ℝ => waitingCost A M y) x = A * H M x :=
  (hasDerivAt_waitingCost hL hR).deriv

/-- The access-cost difference generated by the optimal square-root allocation
    is exactly the canonical `H(x,M)`. -/
theorem accessDifference_eq_H {M x : ℝ}
    (hL : 0 < demandL M x)
    (hR : 0 < demandR x) :
    accessDifference M x = H M x := by
  have hsL : 0 < Real.sqrt (demandL M x) := Real.sqrt_pos.2 hL
  have hsR : 0 < Real.sqrt (demandR x) := Real.sqrt_pos.2 hR
  have hsum : Real.sqrt (demandL M x) + Real.sqrt (demandR x) ≠ 0 :=
    ne_of_gt (add_pos hsL hsR)
  have hsqL : (Real.sqrt (demandL M x)) ^ 2 = demandL M x :=
    Real.sq_sqrt (le_of_lt hL)
  have hsqR : (Real.sqrt (demandR x)) ^ 2 = demandR x :=
    Real.sq_sqrt (le_of_lt hR)
  have hone :
      1 - unconstrainedShare M x =
        Real.sqrt (demandR x) /
          (Real.sqrt (demandL M x) + Real.sqrt (demandR x)) := by
    rw [unconstrainedShare]
    field_simp [hsum]
    ring
  rw [accessDifference, unconstrainedShare, hone, H,
    Real.sqrt_mul (le_of_lt hL)]
  field_simp [ne_of_gt hsL, ne_of_gt hsR, hsum]
  rw [← hsqL, ← hsqR]
  unfold demandL demandR
  ring

/-- Full T4 statement: the marginal minimized waiting cost equals the
    directional waiting/access difference entering shopper choice. -/
theorem operator_envelope_identity {A M x : ℝ}
    (hL : 0 < demandL M x)
    (hR : 0 < demandR x) :
    deriv (fun y : ℝ => waitingCost A M y) x =
      A * accessDifference M x := by
  rw [deriv_waitingCost hL hR, accessDifference_eq_H hL hR]

end

end DirectionalFriction.Envelope
